# Generated by Django 4.1.7 on 2023-03-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('rental_start_date', models.DateField(verbose_name='Дата начала проката')),
                ('rental_finish_date', models.DateField(verbose_name='Дата окончания проката')),
                ('sales_company', models.CharField(max_length=255, verbose_name='Кинокомпания')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зала')),
                ('count_place', models.IntegerField(max_length=100, verbose_name='Количество мест')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('number_of_rows', models.IntegerField(max_length=50, verbose_name='Номер ряда')),
                ('number_of_places', models.IntegerField(max_length=50, verbose_name='Номер места')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie', verbose_name='Фильм')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.saloon', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['movie'],
            },
        ),
    ]
