# Generated by Django 4.1.7 on 2023-03-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_movingtickets_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movingtickets',
            name='operation',
            field=models.CharField(max_length=50, verbose_name='Операция'),
        ),
    ]
